# Generated by Django 5.1.1 on 2024-09-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ICD10",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Наименование")),
                ("code", models.CharField(max_length=20, verbose_name="Код")),
                (
                    "description",
                    models.TextField(verbose_name="Дополнительное описание"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="valueset.icd10",
                    ),
                ),
            ],
            options={
                "verbose_name": "МКБ-10",
                "verbose_name_plural": "МКБ-10",
            },
        ),
    ]
