volumes:
  pgadmin: {}
  postgres_data: {}

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      # Data
      - postgres_data:/var/lib/postgresql/data
      # For binary pg_dump backups
      - ./volumes/postgres/backup:/backup

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
    volumes:
      # Config
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5555:80"

  redis:
    image: redis
    command: ["sh", "-c", "rm -f /data/dump.rdb && redis-server --save ''"]

  web: &web
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
    image: drftreeview/web
    volumes:
      - ./app:/app
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./fixtures:/fixtures
      - ./volumes/logs:/logs
    env_file:
      - ./compose/env.local
    ports:
      - "8000:8000"
    command: /web
